# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: betterish
subtitle: makers of the bettercast
email: hello@betterish.co
description: Real stories, tips, and tools to keep you feeling motivated.
baseurl: "betterish_launch" # the subpath of your site, e.g. /blog
url: "betterish.github.io" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
twitter_username: betterish
instagram_username: betterish

# tiles
tiles-source: episodes
tiles-count: 12

collections:
  episodes:
    output: true
    permalink: /bettercast/:path/


# Build settings
markdown: kramdown
exclude: ["Gemfile", "Gemfile.lock", node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/","docker-compose.yml"]

# Layout settings
home-link-in-menu: yes
